---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность пользоваться кнопками навигации (переходов) между страницами
  - В поле фильтрации товара по ключевому слову, марке или категории должна быть кнопка сброса фильтра
  - Сайт должен иметь форму регистрации пользователя с указанием имени, номера телефона и почтового адреса для связи с покупателем
  - При смене локализации все разделы меню должны быть на языке выбранной локализации
  - Пользователь должен иметь возможность оформить заказ
